MPT-4179 Autorenew is off for subscriptions, created from transfer or…
softwareone-platform/swo-adobe-vipm-extension pull request #263
Opened 2024-10-25 15:49 UTC by ruben-sebrango

…ders for Adobe

2024-10-28 14:48 UTC, d3rky requested changes

2024-10-28 14:48 UTC, d3rky commented on adobe_vipm/flows/fulfillment/transfer.py
> +    if customer_benefits_3yc_status != STATUS_3YC_COMMITTED:
Probably it is better to move this `if` to the upper function. Just because decision should be made before you even fetch subscription

2024-10-28 16:19 UTC, ruben-sebrango commented on adobe_vipm/flows/fulfillment/transfer.py
> +    if customer_benefits_3yc_status != STATUS_3YC_COMMITTED:
Done

2024-10-29 10:05 UTC, d3rky approved these changes

2024-10-29 10:05 UTC, merged