216757 add support for termination orders
softwareone-platform/swo-adobe-vipm-extension pull request #27
Opened 2024-02-08 10:32 UTC by ffaraone

2024-02-08 18:14 UTC, d3rky requested changes

2024-02-08 18:14 UTC, d3rky commented on adobe_vipm/flows/fulfillment.py
> +    for item in order["items"]:
Do you mind making it a little bit more straightforward and avoiding one more nested level?

```
upsize_items = filter(lambda i: t["oldQuantity"] > i["quantity"], order["items"]
search_4_orders = functools.partial(
    adobe_client.search_new_and_returned_orders_by_sku_line_number,
    seller_country,
    customer_id,
)
orders_4_item = map(lambda i: search_4_orders(i["productItemId"], i["lineNumber"]), upsize_items)

for order_to_return, item_to_return, return_order in orders_4_item:
    ...
```

2024-02-08 18:14 UTC, d3rky commented on adobe_vipm/utils.py
> +def get_attempt_count(event):  # pragma: no cover
👍

2024-02-08 18:14 UTC, d3rky commented on devmock/mockgendata.py
> +    console.print(f"[green]✓[/green] Buyer {buyer_id} - {buyer['name']} generated")
Maybe use "Buyer '{buyer['name']'(buyer_id)"?

2024-02-12 09:28 UTC, ffaraone commented on adobe_vipm/flows/fulfillment.py
> +    for item in order["items"]:
Thanks for the good suggestion, unfortunately the `search_new_and_returned_orders_by_sku_line_number` function returns a list of tuples. mapping the function to the filtered list of items makes orders_4_items contains a list of list of tuples. So here I see two options: flatten the list introducing another "well known ;)" function or leaving it as is.
IMO the introduction the flatten function even if it reduce the cognitive complexity of the function, it reduce also the readability. So even if the current implementation is not so elegant I decided to leave it as is.

2024-02-12 09:28 UTC, ffaraone commented on adobe_vipm/utils.py
> +def get_attempt_count(event):  # pragma: no cover
You are welcome :)

2024-02-12 09:29 UTC, ffaraone commented on devmock/mockgendata.py
> +    console.print(f"[green]✓[/green] Buyer {buyer_id} - {buyer['name']} generated")
I think there is no need to change this in a code that will be deleted asap.

2024-02-12 09:58 UTC, d3rky approved these changes

2024-02-12 09:58 UTC, merged